name: Backend CI




on:

push:

branches: [main]

pull_request:

branches: [main]



jobs:

build-and-test:

runs-on: windows-latest



steps:

- name: Checkout code

uses: actions/checkout@v3



- name: Setup .NET

uses: actions/setup-dotnet@v3

with:

dotnet-version: '8.0.x' 



- name: Restore dependencies

run: dotnet restore MatchTracker.sln



- name: Build solution

run: dotnet build MatchTracker.sln --no-restore --configuration Release



- name: Run tests

run: dotnet test MatchTracker.sln --no-build --verbosity normal
